#!/usr/bin/env python3
"""Cross-fit a risk head that consumes proposal-domain foreground pixels.

The input must be produced by ``rerank_cv3_pseudo_with_foreground_gate.py``.
Its ``foreground_probability`` is generated by a fold-specific ConvNeXt gate:
the gate evaluating fold *k* was trained only on the other two formal folds.
This script keeps that outer-fold contract and fits a small held-out risk head
over detector, geometry and foreground evidence.  It intentionally contains
no GT-derived feature; GT is used only to construct training labels.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path
from typing import Any, Mapping

import joblib
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from rsdet.analysis.multi_detector_oer import (
    candidate_validity_labels,
    class_aware_nms_records,
)
from rsdet.evaluation.coco import load_coco_ground_truth
from rsdet.evaluation.protocol import parse_evaluation_protocol
from rsdet.utils.config import load_config

FOREGROUND_COLUMNS = (
    "detector_score",
    "model_y5",
    "model_m3",
    "coarse_ship",
    "coarse_aircraft",
    "coarse_vehicle",
    "log_short_edge",
    "log_area",
    "log_aspect",
    "foreground_probability",
    "foreground_logit",
    "score_x_foreground",
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def normalize_records(rows: list[Mapping[str, Any]]) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for stable_order, raw in enumerate(rows):
        x, y, width, height = (float(value) for value in raw["bbox"])
        probability = float(raw["foreground_probability"])
        if width <= 0.0 or height <= 0.0:
            continue
        if not 0.0 <= probability <= 1.0 or not math.isfinite(probability):
            raise ValueError("foreground_probability must be finite and in [0, 1]")
        fold = int(raw["source_fold"])
        if fold not in {0, 1, 2}:
            raise ValueError(f"invalid source_fold={fold}")
        model = str(raw.get("source_model", "UNKNOWN")).upper()
        if model not in {"Y5", "M3"}:
            raise ValueError(f"invalid source_model={model}")
        output.append(
            {
                **dict(raw),
                "fold": fold,
                "model_key": model,
                "bbox_xyxy": [x, y, x + width, y + height],
                "stable_order": stable_order,
            }
        )
    return output


def build_foreground_features(
    records: list[Mapping[str, Any]], *, category_mapping: Mapping[int, str]
) -> np.ndarray:
    matrix = np.zeros((len(records), len(FOREGROUND_COLUMNS)), dtype=np.float64)
    epsilon = 1e-6
    for index, item in enumerate(records):
        coarse = category_mapping[int(item["category_id"])]
        x0, y0, x1, y1 = (float(value) for value in item["bbox_xyxy"])
        width, height = x1 - x0, y1 - y0
        detector_score = float(item.get("detector_score", item["score"]))
        probability = min(max(float(item["foreground_probability"]), epsilon), 1.0 - epsilon)
        matrix[index] = (
            detector_score,
            float(item["model_key"] == "Y5"),
            float(item["model_key"] == "M3"),
            float(coarse == "ship"),
            float(coarse == "aircraft"),
            float(coarse == "vehicle"),
            math.log1p(min(width, height)),
            math.log1p(width * height),
            math.log(max(width / height, height / width)),
            probability,
            math.log(probability / (1.0 - probability)),
            detector_score * probability,
        )
    if not np.isfinite(matrix).all():
        raise RuntimeError("foreground feature matrix contains NaN/Inf")
    return matrix


def _model(seed: int):
    from sklearn.ensemble import HistGradientBoostingClassifier

    return HistGradientBoostingClassifier(
        max_iter=250,
        learning_rate=0.08,
        max_depth=6,
        l2_regularization=1.0,
        class_weight="balanced",
        random_state=seed,
    )


def _to_coco(records: list[Mapping[str, Any]]) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for item in records:
        x0, y0, x1, y1 = (float(value) for value in item["bbox_xyxy"])
        output.append(
            {
                "image_id": int(item["image_id"]),
                "category_id": int(item["category_id"]),
                "bbox": [x0, y0, x1 - x0, y1 - y0],
                "score": float(item["score"]),
                "source_fold": int(item["fold"]),
                "source_model": str(item["model_key"]),
                "detector_score": float(item.get("detector_score", item["score"])),
                "foreground_probability": float(item["foreground_probability"]),
            }
        )
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ground-truth", type=Path, required=True)
    parser.add_argument("--foreground-predictions", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--project-config", type=Path, default=Path("configs/project.yaml"))
    parser.add_argument("--nms-iou", type=float, default=0.70)
    args = parser.parse_args()

    protocol = parse_evaluation_protocol(load_config(args.project_config))
    gt = load_coco_ground_truth(args.ground_truth)
    raw = json.loads(args.foreground_predictions.read_text(encoding="utf-8"))
    records = class_aware_nms_records(
        normalize_records(raw), iou_threshold=args.nms_iou
    )
    features = build_foreground_features(
        records, category_mapping=protocol.category_mapping
    )
    labels = candidate_validity_labels(
        records,
        gt_boxes=gt,
        category_mapping=protocol.category_mapping,
        iou_thresholds=protocol.iou_thresholds,
    )
    folds = np.asarray([int(item["fold"]) for item in records], dtype=np.int64)
    probabilities = np.full(len(records), np.nan, dtype=np.float64)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    fold_rows: list[dict[str, Any]] = []
    for held_out in (0, 1, 2):
        train = folds != held_out
        validation = folds == held_out
        model = _model(20260829 + held_out)
        model.fit(features[train], labels[train])
        probabilities[validation] = model.predict_proba(features[validation])[:, 1]
        path = args.output_dir / f"foreground_oer_heldout_fold{held_out}.joblib"
        joblib.dump({"model": model, "columns": list(FOREGROUND_COLUMNS)}, path, compress=3)
        fold_rows.append(
            {
                "held_out_fold": held_out,
                "n_train": int(train.sum()),
                "n_validation": int(validation.sum()),
                "train_positive_rate": float(labels[train].mean()),
                "validation_positive_rate": float(labels[validation].mean()),
                "model_sha256": _sha256(path),
            }
        )
    if not np.isfinite(probabilities).all():
        raise RuntimeError("incomplete OOF foreground risk probabilities")

    scored: list[dict[str, Any]] = []
    for item, probability in zip(records, probabilities, strict=True):
        row = dict(item)
        row["score"] = float(probability)
        scored.append(row)
    scored = class_aware_nms_records(scored, iou_threshold=args.nms_iou)
    predictions_path = args.output_dir / "foreground_oer_predictions.json"
    predictions_path.write_text(
        json.dumps(_to_coco(scored), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    summary = {
        "status": "complete",
        "protocol": "pseudo10k_fold_heldout_proposal_pixel_foreground_oer_v1",
        "warning": "deployment-domain proxy only; not an independent hidden-set estimate",
        "columns": list(FOREGROUND_COLUMNS),
        "input_sha256": {
            "ground_truth": _sha256(args.ground_truth),
            "foreground_predictions": _sha256(args.foreground_predictions),
        },
        "input_candidates": len(records),
        "valid_candidates": int(labels.sum()),
        "output_candidates": len(scored),
        "fold_models": fold_rows,
        "predictions_sha256": _sha256(predictions_path),
    }
    (args.output_dir / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
